import type { Context } from "hono";

/**
 * Minimal RPC interface for auth-svc JWKS (service binding).
 */
export interface AuthSvcRpc {
	getJwks(): Promise<{ keys: unknown[] }>;
}

/**
 * Extended environment bindings with custom properties.
 * The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
 */
export type Bindings = Env & {
	/**
	 * Service binding to auth-svc for JWT verification (JWKS).
	 */
	AUTH_SERVICE?: AuthSvcRpc;
	/**
	 * Optional JWKS cache TTL override (seconds).
	 */
	AUTH_JWKS_CACHE_TTL?: string;
	/**
	 * Optional shared secret for POST /api/flags/evaluate without JWT (service-to-service).
	 */
	FLAGS_EVALUATE_INTERNAL_TOKEN?: string;
	/**
	 * Sentry DSN for error tracking.
	 */
	SENTRY_DSN?: string;
};

export type AppContext = Context<{ Bindings: Bindings }>;
export type HandleArgs = [AppContext];
