import type { Context } from "hono";

/**
 * Extended environment bindings with custom properties.
 * The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
 */
export type Bindings = Env & {
	/**
	 * Optional override for tasks cache TTL (seconds).
	 * Must be >= 60. Defaults to 60.
	 */
	TASKS_CACHE_TTL_SECONDS?: string;
	/**
	 * Sentry DSN for error tracking.
	 * If not set, Sentry will be disabled.
	 * Configured via Cloudflare Dashboard secrets or wrangler vars.
	 */
	SENTRY_DSN?: string;
};

export type AppContext = Context<{ Bindings: Bindings }>;
export type HandleArgs = [AppContext];
